version: "3"


services:
  bot:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: bash -c "python3.11 -m app"
    restart: always
    env_file:
      - .env
    volumes:
      - "logs:/data"
