version: "3"


services:
  bot:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: bash -c "python3.11 -m app"
    restart: always
    env_file:
      - .env
    volumes:
      - "logs:/data"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5555:5432"

volumes:
  db:
  logs:
